import {
  Search,
  Bug,
  TrendingUp,
  FileText,
  Mail,
  ShoppingCart,
  Users,
  BarChart3,
  Globe,
  Eye,
  Send,
  MonitorSmartphone,
  type LucideIcon,
} from "lucide-react"

export interface UseCase {
  slug: string
  label: string
  headline: string
  outcome: string
  icon: LucideIcon
  color: string
  heroStat: string
  heroStatLabel: string
  description: string
  steps: { title: string; description: string }[]
  deliverables: string[]
  examplePrompt: string
  faqs: { q: string; a: string }[]
}

export const USE_CASES: UseCase[] = [
  {
    slug: "competitor-intel",
    label: "Competitor Intel",
    headline: "5 competitor reports in 8 min",
    outcome: "5 competitor profiles with pricing, traffic stats, feature matrices, and positioning gaps, exported as a ready-to-share spreadsheet in under 8 minutes.",
    icon: Search,
    color: "emerald",
    heroStat: "5",
    heroStatLabel: "competitor profiles delivered",
    description: "Coasty visits each competitor's website, captures pricing pages, feature lists, traffic estimates, and positioning, then compiles everything into a structured comparison spreadsheet you can share with your team in minutes.",
    steps: [
      { title: "You name your competitors", description: "Paste up to 10 competitor URLs or just describe your market. Coasty finds them automatically." },
      { title: "Coasty visits every page", description: "The agent browses each competitor site, captures pricing, features, messaging, traffic data, and screenshots of key pages." },
      { title: "Analysis is compiled", description: "All data is structured into a side-by-side comparison matrix with your product included for context." },
      { title: "Report is delivered", description: "A shareable spreadsheet with pricing tables, feature grids, traffic stats, and a written summary of positioning gaps." },
    ],
    deliverables: [
      "Side-by-side pricing comparison table",
      "Feature matrix across all competitors",
      "Traffic & growth estimates per competitor",
      "Screenshots of key pages (pricing, homepage, features)",
      "Written positioning gap analysis",
      "Exportable spreadsheet ready for stakeholders",
    ],
    examplePrompt: "Research my top 5 competitors in the project management space. Compare their pricing, features, and positioning against my product at [your-url.com]. Export as a spreadsheet.",
    faqs: [
      { q: "How many competitors can it analyze at once?", a: "Up to 10 competitors in a single run. Each gets a full profile with pricing, features, and traffic data." },
      { q: "Where does the traffic data come from?", a: "Coasty cross-references multiple public sources including SimilarWeb, search visibility, and social presence indicators." },
      { q: "Can I schedule recurring competitor reports?", a: "Yes, set up weekly or monthly competitor monitoring and get notified when pricing, features, or positioning changes." },
    ],
  },
  {
    slug: "qa-bug-reports",
    label: "QA Bug Reports",
    headline: "30+ flows tested in 12 min",
    outcome: "30+ user flows tested, 100% of critical paths covered, every bug screenshotted with repro steps, delivered as a prioritized Notion doc in 12 minutes.",
    icon: Bug,
    color: "rose",
    heroStat: "30+",
    heroStatLabel: "user flows tested per run",
    description: "Coasty opens your app in a real browser and methodically tests every user flow: sign-up, checkout, settings, and edge cases. It screenshots every bug, writes reproduction steps, and delivers a prioritized bug report your dev team can act on immediately.",
    steps: [
      { title: "Point it at your app", description: "Give Coasty your staging URL and optional login credentials. Describe any specific flows or areas to focus on." },
      { title: "Every flow is tested", description: "The agent systematically walks through sign-up, login, navigation, forms, checkout, settings, and edge cases on desktop and mobile viewports." },
      { title: "Bugs are captured", description: "Each issue is screenshotted at the exact moment of failure, with browser console errors, network failures, and the exact steps to reproduce." },
      { title: "Report is prioritized", description: "Bugs are categorized by severity (critical, major, minor, cosmetic) and delivered as a structured doc with screenshots inline." },
    ],
    deliverables: [
      "30+ user flows tested with pass/fail status",
      "Screenshot of every bug at point of failure",
      "Step-by-step reproduction instructions",
      "Browser console errors captured",
      "Severity-ranked priority list",
      "Structured report ready for your dev team",
    ],
    examplePrompt: "Test every user flow on staging.myapp.com: sign-up, login, dashboard, settings, checkout. Screenshot every bug and write repro steps. Prioritize by severity.",
    faqs: [
      { q: "Can it test authenticated flows?", a: "Yes, provide login credentials and Coasty will test all authenticated user journeys including account settings, billing, and admin panels." },
      { q: "Does it test mobile viewports?", a: "Yes, every flow is tested at desktop (1440px), tablet (768px), and mobile (375px) breakpoints automatically." },
      { q: "Can I connect it to Jira or Linear?", a: "The report is delivered as a structured document. You can copy individual bugs directly into your issue tracker with all context preserved." },
    ],
  },
  {
    slug: "seo-gap-analysis",
    label: "SEO Gap Analysis",
    headline: "150 keyword gaps in 15 min",
    outcome: "150+ keyword gaps identified, 10 high-impact content briefs drafted, competitor backlink sources mapped. Full report in 15 minutes.",
    icon: TrendingUp,
    color: "blue",
    heroStat: "150+",
    heroStatLabel: "keyword gaps identified",
    description: "Coasty analyzes your site's search visibility against competitors, finds every keyword they rank for that you don't, maps their backlink sources, and drafts 10 ready-to-write content briefs targeting your highest-opportunity gaps.",
    steps: [
      { title: "Enter your domain", description: "Provide your URL and optionally name competitors, or let Coasty identify them from your search landscape." },
      { title: "Search landscape is mapped", description: "The agent analyzes your current rankings, identifies competitor keywords, and cross-references search volumes and difficulty scores." },
      { title: "Gaps are prioritized", description: "Keywords are ranked by opportunity: high volume, low difficulty, and high relevance to your business." },
      { title: "Content briefs are drafted", description: "10 content briefs are written targeting your best keyword gaps, with titles, outlines, target word counts, and competitor reference URLs." },
    ],
    deliverables: [
      "150+ keyword gap list with volume & difficulty",
      "Competitor keyword overlap matrix",
      "10 ready-to-write content briefs",
      "Backlink source analysis per competitor",
      "Priority-ranked opportunity list",
      "Exportable CSV of all keyword data",
    ],
    examplePrompt: "Analyze SEO gaps for mysite.com against our top 3 competitors. Find keywords they rank for that we don't. Draft 10 content briefs for the highest-opportunity gaps.",
    faqs: [
      { q: "Where does the keyword data come from?", a: "Coasty cross-references Google search results, autocomplete data, and public ranking tools to build a comprehensive keyword landscape." },
      { q: "How are content briefs structured?", a: "Each brief includes a title, target keyword, search volume, suggested outline (H2s/H3s), target word count, and competitor URLs to reference." },
      { q: "Can it track keyword changes over time?", a: "Yes, schedule monthly SEO gap analyses to track how your visibility improves and spot new opportunities as they emerge." },
    ],
  },
  {
    slug: "data-extraction",
    label: "Data Extraction",
    headline: "1,000 rows scraped in 6 min",
    outcome: "1,000+ product listings scraped with prices, specs, and images, cleaned, de-duped, and exported as structured CSV in 6 minutes.",
    icon: FileText,
    color: "violet",
    heroStat: "1,000+",
    heroStatLabel: "rows extracted per run",
    description: "Coasty navigates complex websites, handles pagination, pop-ups, and dynamic loading, extracting structured data from product listings, directories, job boards, or any web source. Data is cleaned, de-duplicated, and exported as a ready-to-use CSV.",
    steps: [
      { title: "Describe what you need", description: "Tell Coasty what data to extract and from where: product prices, job listings, contact directories, or any structured web data." },
      { title: "Pages are navigated", description: "The agent handles pagination, infinite scroll, pop-ups, and dynamic content, visiting every page needed to capture complete data." },
      { title: "Data is extracted", description: "Each record is parsed with all relevant fields (names, prices, descriptions, URLs, images, metadata) into structured rows." },
      { title: "CSV is delivered", description: "Data is cleaned, de-duplicated, validated for completeness, and exported as a formatted CSV or spreadsheet." },
    ],
    deliverables: [
      "1,000+ structured data rows",
      "All fields captured (price, name, specs, URLs, images)",
      "De-duplicated and cleaned dataset",
      "Formatted CSV ready for import",
      "Source URLs preserved for verification",
      "Summary statistics of extracted data",
    ],
    examplePrompt: "Scrape all product listings from [competitor-store.com] including name, price, description, specs, and image URLs. Export as a clean CSV with no duplicates.",
    faqs: [
      { q: "Can it handle sites that require login?", a: "Yes, provide credentials and Coasty will authenticate, navigate, and extract data from behind login walls." },
      { q: "What about sites with infinite scroll?", a: "Coasty handles infinite scroll, lazy loading, pagination, and 'Load More' buttons automatically; it keeps scrolling until all data is captured." },
      { q: "How large can the extraction be?", a: "A single run typically captures 1,000–5,000 records. For larger datasets, schedule multiple runs or use swarm mode for parallel extraction." },
    ],
  },
  {
    slug: "lead-generation",
    label: "Lead Generation",
    headline: "50 qualified leads in 10 min",
    outcome: "50 qualified decision-makers matching your ICP, with verified titles, companies, LinkedIn URLs, and personalized openers, delivered in 10 minutes.",
    icon: Users,
    color: "amber",
    heroStat: "50",
    heroStatLabel: "qualified leads per run",
    description: "Coasty searches LinkedIn, company directories, and industry sites to find decision-makers who match your ideal customer profile. Each lead comes with their name, title, company, LinkedIn URL, and a personalized opening line referencing their role and company.",
    steps: [
      { title: "Define your ICP", description: "Describe your ideal customer: industry, company size, job titles, geography, or any specific criteria." },
      { title: "Prospects are sourced", description: "Coasty searches LinkedIn, company websites, directories, and industry sources to find matching decision-makers." },
      { title: "Leads are qualified", description: "Each prospect is verified against your criteria: title match, company fit, and relevance scoring." },
      { title: "Outreach is personalized", description: "Every lead gets a custom opening line referencing their company, role, and a relevant hook, ready for your outreach." },
    ],
    deliverables: [
      "50 qualified leads matching your ICP",
      "Name, title, company for each lead",
      "LinkedIn profile URLs",
      "Personalized opening lines per lead",
      "Company size and industry data",
      "Exportable CSV for your CRM",
    ],
    examplePrompt: "Find 50 VP of Engineering or CTO-level leads at B2B SaaS companies with 50-500 employees. Include LinkedIn URLs and write a personalized opener for each referencing their company.",
    faqs: [
      { q: "What sources does it search?", a: "LinkedIn, company websites, industry directories, Crunchbase, and other public professional sources." },
      { q: "Are email addresses included?", a: "Coasty captures publicly available contact information. For email enrichment, you can connect the CSV output to tools like Apollo or Hunter." },
      { q: "Can I filter by geography?", a: "Yes, specify countries, regions, or cities in your ICP criteria and only matching leads will be returned." },
    ],
  },
  {
    slug: "site-audit",
    label: "Site Audit",
    headline: "200 pages audited in 9 min",
    outcome: "200+ pages scanned, Core Web Vitals scored, 15+ broken links found, accessibility issues ranked by severity. Full report with fix priorities in 9 minutes.",
    icon: BarChart3,
    color: "emerald",
    heroStat: "200+",
    heroStatLabel: "pages audited per run",
    description: "Coasty crawls your entire site, tests page speed on every page, checks Core Web Vitals, finds broken links and images, audits accessibility compliance, and delivers a fix-priority report so you know exactly what to fix first for maximum impact.",
    steps: [
      { title: "Enter your site URL", description: "Provide your domain and Coasty will discover and crawl every accessible page automatically." },
      { title: "Every page is scanned", description: "Page speed, Core Web Vitals (LCP, FID, CLS), broken links, missing alt text, heading hierarchy, and accessibility issues are checked on every page." },
      { title: "Issues are categorized", description: "Problems are grouped by type and severity: critical performance issues, broken resources, SEO problems, and accessibility violations." },
      { title: "Fix priorities are ranked", description: "Issues are ranked by impact, showing which fixes will improve your site's performance, SEO, and user experience the most." },
    ],
    deliverables: [
      "200+ pages crawled and analyzed",
      "Core Web Vitals scores per page",
      "Broken links and images list",
      "Accessibility violations with WCAG references",
      "Page speed scores with specific bottlenecks",
      "Impact-ranked fix priority list",
    ],
    examplePrompt: "Audit every page on mysite.com. Check page speed, Core Web Vitals, broken links, accessibility, and SEO basics. Rank all issues by impact and tell me what to fix first.",
    faqs: [
      { q: "How many pages can it crawl?", a: "A single audit typically covers 200-500 pages. For larger sites, Coasty prioritizes the most important pages (high traffic, key landing pages) first." },
      { q: "Does it check mobile performance?", a: "Yes, every page is tested at both desktop and mobile viewport sizes, with separate Core Web Vitals scores for each." },
      { q: "Can I schedule recurring audits?", a: "Yes, set up weekly or monthly site audits to track improvements and catch new issues before they affect your users." },
    ],
  },
  {
    slug: "ad-intelligence",
    label: "Ad Intelligence",
    headline: "25 competitor ads in 11 min",
    outcome: "8 competitor landing pages captured, 25+ ad creatives archived, messaging patterns analyzed. Side-by-side teardown delivered in 11 minutes.",
    icon: Eye,
    color: "blue",
    heroStat: "25+",
    heroStatLabel: "ad creatives captured",
    description: "Coasty finds and captures your competitors' active ads, screenshots their landing pages, archives their ad creatives, and writes a detailed analysis of their messaging strategy, so you can see exactly what they're saying and how to differentiate.",
    steps: [
      { title: "Name your competitors", description: "Provide competitor names or domains. Coasty will find their active ads across Google, Meta, and LinkedIn ad libraries." },
      { title: "Ads are captured", description: "Every active ad creative is screenshotted and archived, including copy, images, CTAs, and targeting signals." },
      { title: "Landing pages are recorded", description: "Each ad's destination page is visited, fully screenshotted, and analyzed for messaging, layout, and conversion tactics." },
      { title: "Teardown is written", description: "A written analysis comparing their messaging vs yours, highlighting positioning differences, unique claims, and opportunities." },
    ],
    deliverables: [
      "25+ ad creatives screenshotted and archived",
      "8 competitor landing pages fully captured",
      "Ad copy and CTA analysis per competitor",
      "Messaging pattern breakdown",
      "Side-by-side positioning comparison",
      "Written recommendations for differentiation",
    ],
    examplePrompt: "Find all active ads from [competitor1.com], [competitor2.com], and [competitor3.com]. Screenshot every ad and landing page. Write a teardown comparing their messaging to ours at [your-site.com].",
    faqs: [
      { q: "Which ad platforms does it check?", a: "Google Ads Library, Meta Ad Library, and LinkedIn Ad Library. Coasty also checks for display ads on major publisher sites." },
      { q: "Can it track ad changes over time?", a: "Yes, schedule weekly ad intelligence runs to see when competitors launch new creatives, change messaging, or test new landing pages." },
      { q: "Does it capture video ads?", a: "Coasty captures video ad thumbnails and metadata. For full video archival, it records the first 10 seconds as a preview." },
    ],
  },
  {
    slug: "email-outreach",
    label: "Email Outreach",
    headline: "50 cold emails in 7 min",
    outcome: "50 personalized cold emails drafted, each referencing the prospect's company, role, and a specific pain point, ready to send in 7 minutes.",
    icon: Send,
    color: "violet",
    heroStat: "50",
    heroStatLabel: "personalized emails drafted",
    description: "Coasty researches each prospect's company and role, then drafts a personalized cold email that references specific details like their recent funding round, a blog post they wrote, their team size, or a challenge their company faces. No generic templates.",
    steps: [
      { title: "Upload your lead list", description: "Provide a CSV with names, companies, and emails, or let Coasty generate the list from your ICP criteria." },
      { title: "Each prospect is researched", description: "Coasty visits each prospect's company website and LinkedIn to find specific, relevant details for personalization." },
      { title: "Emails are drafted", description: "Each email is written individually, referencing the prospect's company, role, recent news, or specific pain points relevant to your offer." },
      { title: "Drafts are delivered", description: "50 ready-to-send emails exported as a CSV with prospect name, email, subject line, and personalized body text." },
    ],
    deliverables: [
      "50 individually personalized cold emails",
      "Custom subject lines per prospect",
      "Company-specific pain point references",
      "Role-relevant value propositions",
      "Ready-to-send CSV format",
      "Research notes per prospect",
    ],
    examplePrompt: "Draft 50 cold emails to these leads [upload CSV]. Research each prospect's company and write a personalized email referencing their specific situation. Our product helps with [your value prop].",
    faqs: [
      { q: "How personalized are the emails really?", a: "Each email references 2-3 specific details about the prospect: their company's product, a recent milestone, their team size, or a challenge visible from their website. No two emails are the same." },
      { q: "Can I set the tone and style?", a: "Yes, specify casual, professional, or direct tone. You can also provide a sample email and Coasty will match your voice." },
      { q: "Does it send the emails?", a: "Coasty drafts the emails and exports them. You review and send through your own email tool, keeping you in full control." },
    ],
  },
  {
    slug: "design-review",
    label: "Design Review",
    headline: "12 breakpoints tested in 8 min",
    outcome: "12 breakpoints tested across mobile, tablet, and desktop, 20+ layout issues screenshotted with CSS fix suggestions. Report in 8 minutes.",
    icon: MonitorSmartphone,
    color: "rose",
    heroStat: "12",
    heroStatLabel: "breakpoints tested per page",
    description: "Coasty opens your site at every breakpoint, from 320px mobile to 2560px ultrawide, screenshots each view, identifies layout breaks, overflow issues, and responsive failures, then suggests specific CSS fixes for each problem.",
    steps: [
      { title: "Enter your URL", description: "Provide the pages to test: homepage, key landing pages, or your entire site." },
      { title: "Every breakpoint is tested", description: "Each page is rendered at 12 viewport widths: 320, 375, 414, 428, 768, 834, 1024, 1280, 1440, 1680, 1920, and 2560px." },
      { title: "Issues are captured", description: "Layout breaks, text overflow, image distortion, touch target sizes, and spacing issues are screenshotted at the exact breakpoint where they occur." },
      { title: "Fixes are suggested", description: "Each issue comes with a specific CSS fix suggestion (media query, flexbox adjustment, or spacing change) ready to implement." },
    ],
    deliverables: [
      "12 breakpoint screenshots per page",
      "20+ layout issues identified and screenshotted",
      "Specific CSS fix suggestion per issue",
      "Touch target size audit (mobile)",
      "Typography readability check per viewport",
      "Priority-ranked fix list",
    ],
    examplePrompt: "Test the responsive design of mysite.com at every breakpoint from 320px to 2560px. Screenshot every layout issue and suggest the exact CSS fix for each one.",
    faqs: [
      { q: "Which pages does it test?", a: "You can specify individual URLs or let Coasty crawl your site and test the most important pages automatically (homepage, pricing, features, blog)." },
      { q: "Does it test actual CSS or just visual issues?", a: "Both. Coasty identifies visual layout breaks and inspects the DOM to suggest specific CSS property changes (media queries, flex adjustments, max-widths)." },
      { q: "Can it compare before and after?", a: "Yes, run a design review, implement fixes, then run again. Coasty will show which issues are resolved and flag any new ones." },
    ],
  },
  {
    slug: "price-monitoring",
    label: "Price Monitoring",
    headline: "200 SKUs compared in 10 min",
    outcome: "5 competitor price sheets compared across 200+ SKUs, with promotions, availability, and margin gaps flagged in a live spreadsheet in 10 minutes.",
    icon: ShoppingCart,
    color: "amber",
    heroStat: "200+",
    heroStatLabel: "SKUs compared per run",
    description: "Coasty visits competitor stores, captures current pricing on hundreds of products, tracks promotions and availability, and builds a comparison spreadsheet showing exactly where you're priced above, below, or at parity, with margin gap analysis.",
    steps: [
      { title: "List your competitors", description: "Provide competitor store URLs and optionally your own product catalog for direct comparison." },
      { title: "Prices are captured", description: "Coasty navigates each competitor's product pages, capturing current prices, sale prices, bundle deals, and availability status." },
      { title: "Data is matched", description: "Products are matched across competitors by name, SKU, or category, creating accurate apples-to-apples comparisons." },
      { title: "Comparison is delivered", description: "A spreadsheet showing your price vs each competitor per SKU, with promotions flagged and margin gaps calculated." },
    ],
    deliverables: [
      "200+ SKU price comparison across 5 competitors",
      "Current vs sale price tracking",
      "Availability and stock status per SKU",
      "Promotion and bundle deal alerts",
      "Margin gap analysis per product",
      "Exportable comparison spreadsheet",
    ],
    examplePrompt: "Compare our product prices against [competitor1.com] through [competitor5.com] across all overlapping SKUs. Flag where we're more than 10% above or below. Include any active promotions.",
    faqs: [
      { q: "How does it match products across different sites?", a: "Coasty matches by product name, model number, and category. For ambiguous matches, it flags them for your review rather than guessing." },
      { q: "Can it track prices over time?", a: "Yes, schedule daily or weekly price monitoring runs. Coasty will highlight price changes, new promotions, and trends in a historical view." },
      { q: "Does it work for SaaS pricing?", a: "Yes, it captures plan names, pricing tiers, feature inclusions, and any promotional pricing or annual discount rates." },
    ],
  },
  {
    slug: "market-research",
    label: "Market Research",
    headline: "40 data points in 14 min",
    outcome: "$2.4B TAM calculated, 12 key players profiled, 3-year growth trend charted, sourced from 40+ data points, compiled in 14 minutes.",
    icon: Globe,
    color: "blue",
    heroStat: "40+",
    heroStatLabel: "data points sourced",
    description: "Coasty researches your market from scratch, calculating total addressable market, profiling key players, charting growth trends, and sourcing everything from industry reports, public filings, and market data. The results are delivered as a shareable report with citations.",
    steps: [
      { title: "Define your market", description: "Describe your industry, target segment, or the specific market question you need answered." },
      { title: "Sources are gathered", description: "Coasty searches industry reports, public filings, news articles, analyst estimates, and market databases for relevant data points." },
      { title: "Analysis is compiled", description: "TAM/SAM/SOM is calculated, key players are profiled with revenue and market share estimates, and growth trends are charted." },
      { title: "Report is delivered", description: "A structured market research report with executive summary, data tables, player profiles, and full source citations." },
    ],
    deliverables: [
      "TAM / SAM / SOM calculation with methodology",
      "12 key player profiles with estimated revenue",
      "3-year growth trend data and projections",
      "Market segmentation breakdown",
      "40+ cited data sources",
      "Executive summary for stakeholder presentations",
    ],
    examplePrompt: "Research the AI agent market in 2026. Calculate TAM, profile the top 12 players, chart 3-year growth trends, and cite every source. Format as a report I can present to investors.",
    faqs: [
      { q: "How reliable is the TAM calculation?", a: "Coasty uses multiple estimation methods (top-down, bottom-up) and cites every source. The report includes methodology notes so you can validate the approach." },
      { q: "Can it research niche markets?", a: "Yes, even for emerging or niche markets where data is sparse, Coasty triangulates from adjacent markets, funding data, and industry signals." },
      { q: "Is the report investor-ready?", a: "The format is designed for stakeholder presentations: executive summary, key metrics, visual data, and full citations. You may want to add your own strategic commentary." },
    ],
  },
  {
    slug: "email-campaigns",
    label: "Email Campaigns",
    headline: "100 emails personalized in 9 min",
    outcome: "3-email nurture sequence written for 100 prospects, each personalized with company context and pain points, campaign-ready in 9 minutes.",
    icon: Mail,
    color: "emerald",
    heroStat: "100",
    heroStatLabel: "personalized emails per campaign",
    description: "Coasty builds full email campaigns, not just single emails. It researches each prospect, writes a 3-email nurture sequence personalized to their company and role, and delivers everything formatted and ready to load into your email tool.",
    steps: [
      { title: "Define your campaign", description: "Describe your offer, target audience, and campaign goal (demo booking, trial sign-up, event registration, etc.)." },
      { title: "Prospects are researched", description: "Each prospect's company, role, and relevant context is researched to inform personalization across all 3 emails." },
      { title: "Sequences are written", description: "3 emails per prospect: intro with personalized hook, value-add follow-up, and final CTA, each building on the last." },
      { title: "Campaign is exported", description: "All 300 emails (3 × 100) delivered as a CSV with prospect name, email, sequence number, subject line, and body." },
    ],
    deliverables: [
      "3-email nurture sequence per prospect",
      "100 prospects × 3 emails = 300 personalized emails",
      "Custom subject lines per email",
      "Company-specific personalization in every email",
      "Suggested send cadence (Day 1, 3, 7)",
      "Campaign-ready CSV for import",
    ],
    examplePrompt: "Create a 3-email nurture campaign for these 100 prospects [upload CSV]. Goal: book a demo. Research each company and personalize every email. Export campaign-ready for Mailchimp.",
    faqs: [
      { q: "What's the difference from Email Outreach?", a: "Email Outreach drafts single cold emails. Email Campaigns builds multi-touch nurture sequences: 3 emails per prospect with escalating urgency and different angles." },
      { q: "Can I customize the number of emails in the sequence?", a: "Yes, specify 2, 3, 4, or 5 emails per sequence. Each additional email adds a new angle or urgency driver." },
      { q: "Does it handle unsubscribe compliance?", a: "Coasty drafts the content. Compliance elements (unsubscribe links, sender info) should be added by your email platform, which handles this automatically." },
    ],
  },
]

export const USE_CASE_COLORS: Record<string, { text: string; bg: string; border: string; bgSolid: string }> = {
  emerald: { text: "text-emerald-500 dark:text-emerald-400", bg: "bg-emerald-500/10 dark:bg-emerald-400/10", border: "border-emerald-500/20 dark:border-emerald-400/20", bgSolid: "bg-emerald-500" },
  rose:    { text: "text-rose-500 dark:text-rose-400",       bg: "bg-rose-500/10 dark:bg-rose-400/10",       border: "border-rose-500/20 dark:border-rose-400/20",       bgSolid: "bg-rose-500" },
  blue:    { text: "text-blue-500 dark:text-blue-400",       bg: "bg-blue-500/10 dark:bg-blue-400/10",       border: "border-blue-500/20 dark:border-blue-400/20",       bgSolid: "bg-blue-500" },
  violet:  { text: "text-violet-500 dark:text-violet-400",   bg: "bg-violet-500/10 dark:bg-violet-400/10",   border: "border-violet-500/20 dark:border-violet-400/20",   bgSolid: "bg-violet-500" },
  amber:   { text: "text-amber-500 dark:text-amber-400",     bg: "bg-amber-500/10 dark:bg-amber-400/10",     border: "border-amber-500/20 dark:border-amber-400/20",     bgSolid: "bg-amber-500" },
}

export function getUseCaseBySlug(slug: string): UseCase | undefined {
  return USE_CASES.find((uc) => uc.slug === slug)
}
