import React from 'react'
import { useChatStore } from '../stores/chat-store'
import type { ChatMessage, ToolInvocation } from '../stores/chat-store'

/* ────────────────────────────────────────────────────────────
   StreamingTicker

   Cinematic single-line readout for the collapsed pill. Pure
   typography — no icons, no chrome — just the agent's current
   activity rendering as backlit text that dissolves between
   scenes (tool calls, streaming text, idle "thinking…"). Reads
   like a film subtitle, not a UI label.
   ──────────────────────────────────────────────────────────── */

/**
 * Friendly verb-phrase labels for every tool the backend can emit.
 * Covers both the static chat_vm_tools.py registry and the dynamic
 * cua_* tools generated by the CUA executor. Looked up after stripping
 * the cua_/browser_ prefix, so a brand-new cua_foo_bar tool will still
 * produce a readable "Foo bar" via the humanize fallback.
 */
const TOOL_LABELS: Record<string, string> = {
  // Pointer / keyboard primitives
  click: 'Clicking',
  double_click: 'Double-clicking',
  click_with_modifiers: 'Clicking',
  type: 'Typing',
  type_text: 'Typing',
  key: 'Pressing a key',
  key_press: 'Pressing a key',
  key_combo: 'Pressing keys',
  shortcut: 'Pressing a shortcut',
  scroll: 'Scrolling',
  drag: 'Dragging',
  move: 'Moving the cursor',
  wait: 'Waiting',
  done: 'Wrapping up',
  fail: 'Reporting back',
  raw: 'Sending raw input',

  // Vision
  screenshot: 'Looking at the screen',
  detect_elements: 'Finding elements',
  ocr: 'Reading text from the screen',

  // Browser
  browser_open: 'Opening the browser',
  browser_connect: 'Connecting to the browser',
  browser_close: 'Closing the browser',
  browser_navigate: 'Navigating to a page',
  browser_click: 'Clicking a link',
  browser_type: 'Typing in the browser',
  browser_scroll: 'Scrolling the page',
  browser_screenshot: 'Capturing the browser',
  browser_dom: 'Reading the page',
  browser_get_dom: 'Reading the page',
  browser_get_clickables: 'Finding buttons',
  browser_get_context: 'Reading the page',
  browser_state: 'Checking the browser',
  browser_info: 'Reading browser info',
  browser_analyze_form: 'Analyzing the form',
  browser_fill_form_js: 'Filling the form',
  browser_list_tabs: 'Listing tabs',
  browser_open_tab: 'Opening a new tab',
  browser_close_tab: 'Closing the tab',
  browser_switch_tab: 'Switching tabs',
  browser_execute: 'Running browser script',
  browser_wait: 'Waiting for the page',

  // Terminal
  terminal_connect: 'Opening a terminal',
  terminal_execute: 'Running a command',
  terminal_type: 'Typing in the terminal',
  terminal_read: 'Reading terminal output',
  terminal_clear: 'Clearing the terminal',
  terminal_close: 'Closing the terminal',
  execute_command: 'Running a command',

  // Files & directories
  file_read: 'Reading a file',
  file_write: 'Writing a file',
  file_edit: 'Editing a file',
  file_append: 'Appending to a file',
  file_delete: 'Deleting a file',
  file_exists: 'Checking a file',
  file_upload: 'Uploading a file',
  file_download: 'Downloading a file',
  file_list_downloads: 'Listing downloads',
  directory_list: 'Listing files',
  directory_delete: 'Deleting a folder',

  // Window management
  list_windows: 'Listing windows',
  switch_window: 'Switching window',
  switch_to_window: 'Switching window',
  arrange_windows: 'Arranging windows',
  window_operation: 'Adjusting the window',
  move_window: 'Moving the window',

  // Search & credentials
  search: 'Searching the web',
  web_search: 'Searching the web',
  credential_lookup: 'Looking up a credential',
  lookup_credential: 'Looking up a credential',
  fill_credential: 'Filling a credential',
  fill_credential_field: 'Filling a credential',

  // Shared memory & swarm
  read_shared_memory: 'Reading shared memory',
  write_shared_memory: 'Writing to shared memory',
  list_shared_memory: 'Listing shared memory',
  send_swarm_message: 'Sending a swarm message',
  broadcast_swarm_message: 'Broadcasting a message',
  read_swarm_messages: 'Reading swarm messages',

  // P0 collaboration
  request_help: 'Requesting help',
  wait_for_dependency: 'Waiting on a teammate',
  claim_expertise: 'Claiming expertise',
  propose_decision: 'Proposing a decision',
  resume_own_task: 'Resuming work',

  // Email & delegation
  send_email: 'Sending an email',
  read_emails: 'Reading email',
  delegate_task: 'Delegating a task',
  delegate: 'Delegating',
}

/** Title-case a snake_case verb into a readable phrase. */
export function humanize(name: string): string {
  if (!name) return 'Working'
  const words = name.split('_').filter(Boolean)
  if (words.length === 0) return 'Working'
  return words[0].charAt(0).toUpperCase() + words[0].slice(1) +
    (words.length > 1 ? ' ' + words.slice(1).join(' ') : '')
}

/** Resolve backend toolName → readable phrase. */
export function labelForTool(toolName: string): string {
  if (TOOL_LABELS[toolName]) return TOOL_LABELS[toolName]
  const stripped = toolName.replace(/^(cua_|browser_)/, '')
  if (stripped !== toolName && TOOL_LABELS[stripped]) return TOOL_LABELS[stripped]
  return humanize(stripped)
}

export type TickerEvent =
  | { kind: 'tool';     key: string; label: string }
  | { kind: 'text';     key: string; label: string }
  | { kind: 'thinking'; key: string; label: string }

export function deriveEvent(messages: ChatMessage[]): TickerEvent {
  const last = messages[messages.length - 1]
  if (!last || last.role !== 'assistant') {
    return { kind: 'thinking', key: 'k-thinking', label: 'Thinking…' }
  }

  // Most-recent pending tool wins
  const tools: ToolInvocation[] = last.toolInvocations ?? []
  for (let i = tools.length - 1; i >= 0; i--) {
    const t = tools[i]
    if (t.state === 'pending') {
      return {
        kind: 'tool',
        key: `tool:${t.toolCallId}`,
        label: labelForTool(t.toolName),
      }
    }
  }

  // Otherwise, sanitized tail of the assistant text
  const cleaned = (last.content ?? '')
    .replace(/<cua-section[\s\S]*?<\/cua-section>/g, '')
    .replace(/<[^>]+>/g, '')
    .replace(/```[\s\S]*?```/g, '')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/[*_#>]/g, '')
    .replace(/\s+/g, ' ')
    .trim()

  if (cleaned) {
    // Trim to fit centered in the pill (~250px @ 14px font ≈ 56 chars).
    const MAX = 56
    const tail = cleaned.length > MAX ? '…' + cleaned.slice(-(MAX - 1)) : cleaned
    return { kind: 'text', key: `text:${last.id}`, label: tail }
  }

  return { kind: 'thinking', key: `work:${last.id}`, label: 'Working…' }
}

function TickerRow({ event, animate }: { event: TickerEvent; animate: 'in' | 'out' | 'none' }) {
  const cls = animate === 'in' ? 'ticker-in' : animate === 'out' ? 'ticker-out' : ''
  return (
    <div className={`${cls} absolute inset-0 flex items-center justify-center px-2`}>
      {/* leading-[1.4] gives 14px text a 19.6px line-box so descenders
          (g, j, p, q, y) sit comfortably above the container's bottom edge. */}
      <span className="whitespace-nowrap text-[14px] leading-[1.4] shimmer-text font-medium tracking-tight">
        {event.label}
      </span>
    </div>
  )
}

export function StreamingTicker() {
  const messages = useChatStore((s) => s.messages)
  const isStreaming = useChatStore((s) => s.isStreaming)

  const next = React.useMemo(() => deriveEvent(messages), [messages])

  const [current, setCurrent] = React.useState<TickerEvent>(next)
  const [previous, setPrevious] = React.useState<TickerEvent | null>(null)

  React.useEffect(() => {
    if (next.key === current.key) {
      if (next.label !== current.label) setCurrent(next)
      return
    }
    setPrevious(current)
    setCurrent(next)
    const t = setTimeout(() => setPrevious(null), 320)
    return () => clearTimeout(t)
  }, [next.key, next.label])

  if (!isStreaming) return null

  return (
    <div
      className="ticker-mask relative flex-1 min-w-0 h-7 overflow-hidden"
      aria-live="polite"
      aria-label={current.label}
    >
      {previous && <TickerRow event={previous} animate="out" />}
      <TickerRow event={current} animate={previous ? 'in' : 'none'} />
    </div>
  )
}
